FROM python:3.12-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Expose port
EXPOSE 8080

# Command to run the application using Uvicorn
CMD ["uvicorn", "app.main:create_app", "--host", "0.0.0.0", "--port", "8080", "--factory"]
